### ISSUE TITLE
[PE-D][Tester D] Lack of error handling in saving file

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T11-1/tp#160]
While mentioned in the user guide to not edit the files directly, should the user unintentionally do so, it leads to the errors being brought forward to the next session. Do consider include error handling such as wiping the entire file to account for this! (Edited responsibility in the favourites.txt file and reopened the app for the error below to occur)

![Screenshot 2024-04-05 at 4.59.13 PM.png](https://raw.githubusercontent.com/dextboy/ped/main/files/ca272335-1afd-4628-9e3b-986302a288ef.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: dextboy/ped#4

**Comment by damiwee** [comment]
Thank you for your insights. While it is possible to check for corrupted files (aka files that have been directly edited in this case), we feel that it would not be wise to completely wipe the entire file automatically for the user, just in case the user wishes to salvage the data. To partially address the issue you have brought up, we have added additional comments in our user guide FAQ to guide users on what to do in the event they find that their files have become corrupted due to them manually editing the text files. Thanks
